export type NavItem = { label: string; href: string };
export type NavGroup = { label: string; href: string; items: NavItem[] };

export const navGroups: NavGroup[] = [
  {
    label: "Who We Are",
    href: "/who-we-are",
    items: [
      { label: "About DIGINFO", href: "/who-we-are/about-diginfo" },
      { label: "Vision & Strategy", href: "/who-we-are/vision-and-strategy" },
      { label: "Leadership", href: "/who-we-are/leadership" },
      { label: "Our Journey", href: "/who-we-are/our-journey" },
      { label: "Partnerships", href: "/who-we-are/partnerships" },
      { label: "Careers", href: "/who-we-are/careers" },
    ],
  },
  {
    label: "What We Do",
    href: "/what-we-do",
    items: [
      { label: "Cyber Resilience", href: "/what-we-do/cyber-resilience" },
      { label: "Secure Digital Transformation", href: "/what-we-do/secure-digital-transformation" },
      { label: "Cloud & Platform Modernization", href: "/what-we-do/cloud-platform-modernization" },
      { label: "Governance, Risk & Assurance", href: "/what-we-do/governance-risk-assurance" },
      { label: "AI & Intelligence Services", href: "/what-we-do/ai-intelligence-services" },
      { label: "Education & Workforce Development", href: "/what-we-do/education-workforce-development" },
      { label: "Technology Manufacturing & Product Innovation", href: "/what-we-do/technology-manufacturing-product-innovation" },
      { label: "Business Continuity & Growth Enablement", href: "/what-we-do/business-continuity-growth-enablement" },
    ],
  },
  {
    label: "Industries",
    href: "/industries",
    items: [
      { label: "Government & Public Sector", href: "/industries/government-public-sector" },
      { label: "Banking & Finance", href: "/industries/banking-finance" },
      { label: "Telecom", href: "/industries/telecom" },
      { label: "Healthcare", href: "/industries/healthcare" },
      { label: "Education", href: "/industries/education" },
      { label: "Critical Infrastructure", href: "/industries/critical-infrastructure" },
      { label: "Enterprise & Technology", href: "/industries/enterprise-technology" },
      { label: "Manufacturing & Industrial", href: "/industries/manufacturing-industrial" },
    ],
  },
  {
    label: "Innovation",
    href: "/innovation",
    items: [
      { label: "DGBRAIN AI Intelligence Engine", href: "/innovation/dgbrain-ai-intelligence-engine" },
      { label: "Research & Development", href: "/innovation/research-and-development" },
      { label: "Product Engineering", href: "/innovation/product-engineering" },
      { label: "Technology Manufacturing", href: "/innovation/technology-manufacturing" },
      { label: "Cybersecurity Research", href: "/innovation/cybersecurity-research" },
      { label: "Responsible AI & Human Review", href: "/innovation/responsible-ai-human-review" },
      { label: "Security Validation & Bug Bounty", href: "/innovation/security-validation-bug-bounty" },
    ],
  },
  {
    label: "Ecosystem",
    href: "/ecosystem",
    items: [
      { label: "Ecosystem Overview", href: "/ecosystem" },
      { label: "DGMAGAZINE", href: "/ecosystem/dgmagazine" },
      { label: "DGACADEMY", href: "/ecosystem/dgacademy" },
      { label: "DGCLOUD", href: "/ecosystem/dgcloud" },
      { label: "THREATASSURANCE", href: "/ecosystem/threat-assurance" },
      { label: "DGLABS", href: "/ecosystem/dglabs" },
      { label: "NATIVESECURITY", href: "/ecosystem/nativesecurity" },
      { label: "DGBRAIN", href: "/innovation/dgbrain-ai-intelligence-engine" },
      { label: "DGHUB", href: "/ecosystem/dghub" },
      { label: "DGEnterprise", href: "/ecosystem/dgenterprise" },
      { label: "DGSHOP", href: "/ecosystem/dgshop" },
      { label: "DG Nexus", href: "/ecosystem/dg-nexus" },
      { label: "Advanced LMS", href: "/ecosystem/advanced-lms" },
    ],
  },
  {
    label: "Insights",
    href: "/insights",
    items: [
      { label: "Research", href: "/insights/research" },
      { label: "Cyber Intelligence", href: "/insights/cyber-intelligence" },
      { label: "Executive Perspectives", href: "/insights/executive-perspectives" },
      { label: "Articles & Publications", href: "/insights/articles-publications" },
      { label: "News", href: "/insights/news" },
      { label: "Events", href: "/insights/events" },
      { label: "Case Studies", href: "/insights/case-studies" },
    ],
  },
  {
    label: "Contact",
    href: "/contact",
    items: [
      { label: "General Inquiry", href: "/contact/general-inquiry" },
      { label: "Request Consultation", href: "/contact/request-consultation" },
      { label: "Product Inquiry", href: "/contact/product-inquiry" },
      { label: "Partnership Inquiry", href: "/contact/partnership-inquiry" },
      { label: "Company Profile Request", href: "/contact/company-profile-request" },
      { label: "Media Inquiry", href: "/contact/media-inquiry" },
      { label: "Careers Inquiry", href: "/contact/careers-inquiry" },
      { label: "Security Disclosure", href: "/contact/security-disclosure" },
    ],
  },
];
