// import type { MetadataRoute } from "next";

// const routes = [
//   "",
//   "/who-we-are",
//   "/who-we-are/about-diginfo",
//   "/who-we-are/vision-and-strategy",
//   "/who-we-are/leadership",
//   "/who-we-are/our-journey",
//   "/who-we-are/partnerships",
//   "/who-we-are/careers",
//   "/what-we-do",
//   "/what-we-do/cyber-resilience",
//   "/what-we-do/secure-digital-transformation",
//   "/what-we-do/cloud-platform-modernization",
//   "/what-we-do/governance-risk-assurance",
//   "/what-we-do/ai-intelligence-services",
//   "/what-we-do/education-workforce-development",
//   "/what-we-do/technology-manufacturing-product-innovation",
//   "/what-we-do/business-continuity-growth-enablement",
//   "/industries",
//   "/industries/government-public-sector",
//   "/industries/banking-finance",
//   "/industries/telecom",
//   "/industries/healthcare",
//   "/industries/education",
//   "/industries/critical-infrastructure",
//   "/industries/enterprise-technology",
//   "/industries/manufacturing-industrial",
//   "/innovation",
//   "/innovation/dgbrain-ai-intelligence-engine",
//   "/innovation/research-and-development",
//   "/innovation/product-engineering",
//   "/innovation/technology-manufacturing",
//   "/innovation/cybersecurity-research",
//   "/innovation/responsible-ai-human-review",
//   "/innovation/security-validation-bug-bounty",
//   "/ecosystem",
//   "/ecosystem/dgmagazine",
//   "/ecosystem/dgacademy",
//   "/ecosystem/dgcloud",
//   "/ecosystem/threat-assurance",
//   "/ecosystem/dglabs",
//   "/ecosystem/nativesecurity",
//   "/ecosystem/dghub",
//   "/ecosystem/dgenterprise",
//   "/ecosystem/dgshop",
//   "/ecosystem/dg-nexus",
//   "/ecosystem/advanced-lms",
//   "/ecosystem/dg-career",
//   "/ecosystem/dg-family",
//   "/ecosystem/dg-care",
//   "/ecosystem/dg-engineering",
//   "/ecosystem/dg-nsos",
//   "/ecosystem/cyber-kids",
//   "/ecosystem/diginfo-innovatech",
//   "/insights",
//   "/insights/research",
//   "/insights/cyber-intelligence",
//   "/insights/executive-perspectives",
//   "/insights/articles-publications",
//   "/insights/news",
//   "/insights/events",
//   "/insights/case-studies",
//   "/contact",
//   "/contact/general-inquiry",
//   "/contact/request-consultation",
//   "/contact/product-inquiry",
//   "/contact/partnership-inquiry",
//   "/contact/company-profile-request",
//   "/contact/media-inquiry",
//   "/contact/careers-inquiry",
//   "/contact/security-disclosure",
//   "/company-profile",
//   "/search",
//   "/sign-in",
//   "/newsletter",
//   "/sitemap",
//   "/legal/privacy-policy",
//   "/legal/terms-of-use",
//   "/legal/cookie-policy",
//   "/legal/responsible-disclosure",
//   "/legal/accessibility",
// ];

// export default function sitemap(): MetadataRoute.Sitemap {
//   return routes.map((route) => ({
//     url: `https://diginfo.net${route}`,
//     lastModified: new Date(),
//     changeFrequency: "weekly",
//     priority: route === "" ? 1 : 0.8,
//   }));
// }
